  # config.yaml
# ───────────────────────────────────────────────────────────────
# Global settings (apply to every run unless you override them)
# ───────────────────────────────────────────────────────────────
start:  "2000-01-01"       # back-test begins (YYYY-MM-DD)
end:    "2020-01-01"       # back-test ends
capital:    1000          # starting cash in account currency
commission: 0.001          # 0.1 % per trade
slippage:   0.0005         # 0.05 % slippage
output_csv: DataManagement\data\PowerBi\results.csv    # summary results written here

strats:
#  - AdxBreakout
#  - AtrChannelReversion
#  - AtrTrailingTrend
#  - BollingerBreakout
#  - BuyAndHold
#  - DonchianTurtle
#  - EmaCross
  - GoldenCross
#  - IchimokuTrend
#  - KeltnerBreakout
#  - MacdSignal
#  - MaEnvelope
#  - MonthlyRotator
#  - Rsi2
#  - RsiStochCombo
#  - SmaCross
#  - TwelveMonthMomentum
#  - VwapReversion



symbols:
  - SPY
#  - QQQ
#  - MTUM
#  - EEM
#  - TLT
#  - GLD
#  - IEF
#  - MSFT
#  - AAPL
#  - NVDA
#  - META
#  - BTC
#  - IBM
#  - KO