  # config.yaml
# ───────────────────────────────────────────────────────────────
# Global settings (apply to every run unless you override them)
# ----------------------------------------------------------------
start:  "2005-01-01"       # back-test begins (YYYY-MM-DD)
end:    "2020-01-01"       # back-test ends
capital:    1000          # starting cash in account currency
commission: 0.001          # 0.1 % per trade
output_csv: results.csv    # summary results written here

strats:
  - AdxBreakout
  - AtrChannelReversion
  - AtrTrailingTrend
  - BollingerBreakout
  - BuyAndHold
  - DonchianTurtle
  - EmaCross
  - GoldenCross
  - GoldenCross
  - IchimokuTrend
  - KeltnerBreakout
  - MacdSignal
  - MaEnvelope
  - MonthlyRotator
  - Rsi2
  - RsiStochCombo
  - SmaCross
  - TwelveMonthMomentum
  - VwapReversion



symbols:
  - SPY
  - QQQ
  - MTUM
  - EEM
  - TLT
  - GLD
  - IEF
  - MSFT
  - AAPL
  - NVDA
  - META
  - BTC

  - A
  - AA
  - AACB
  - AACBR
  - AACBU
  - AACG
  - AACI
  - AACIU
  - AACIW
  - AACT
  - AAL
  - AAM
  - AAME
  - AAMI
  - AAOI
  - AAON
  - AAP
  - AAPG
  - AAPL
  - AARD
  - AAT
  - AAUC
  - AB
  - ABAT
  - ABBV
  - ABCB
  - ABCL
  - ABEO
  - ABEV
  - ABG
  - ABL
  - ABLLL
  - ABLLW
  - ABLV
  - ABM
  - ABNB
  - ABOS
  - ABP
  - ABPWW
  - ABR
  - ABSI
  - ABT
  - ABTS
  - ABUS
  - ABVC
  - ABVE
  - ABVEW
  - ABVX
  - AC
  - ACA
  - ACAD
  - ACB
  - ACCO
  - ACCS
  - ACDC
  - ACEL
  - ACET
  - ACGL
  - ACGLN
  - ACGLO
  - ACHC
  - ACHR
  - ACHV
  - ACI
  - ACIC
  - ACIU
  - ACIW
  - ACLS
  - ACLX
  - ACM
  - ACMR
  - ACN
  - ACNB
  - ACNT
  - ACOG
  - ACON
  - ACONW
  - ACP
  - ACR
  - ACRE
  - ACRS
  - ACRV
  - ACT
  - ACTG
  - ACTU
  - ACU
  - ACV
  - ACVA
  - ACXP
  - ADAG
  - ADAP
  - ADBE
  - ADC
  - ADCT
  - ADD
  - ADEA
  - ADGM
  - ADI
  - ADIL
  - ADM
  - ADMA
  - ADN
  - ADNT
  - ADNWW
  - ADP
  - ADPT
  - ADSE
  - ADSEW
  - ADSK
  - ADT
  - ADTN
  - ADTX
  - ADUR
  - ADUS
  - ADV
  - ADVB
  - ADVM
  - ADVWW
  - ADX
  - ADXN
  - AEBI
  - AEE
  - AEF
  - AEFC
  - AEG
  - AEHL
  - AEHR
  - AEI
  - AEIS
  - AEM
  - AEMD
  - AENT
  - AENTW
  - AEO
  - AEON
  - AEP
  - AER
  - AERT
  - AERTW
  - AES
  - AESI
  - AEVA
  - AEVAW
  - AEYE
  - AFB
  - AFBI
  - AFCG
  - AFG
  - AFGB
  - AFGC
  - AFGD
  - AFGE
  - AFJK
  - AFJKR
  - AFL
  - AFRI
  - AFRIW
  - AFRM
  - AFYA
  - AG
  - AGAE
  - AGCO
  - AGD
  - AGEN
  - AGFY
  - AGH
  - AGI
  - AGIO
  - AGL
  - AGM
  - AGMH
  - AGNC
  - AGNCL
  - AGNCM
  - AGNCN
  - AGNCO
  - AGNCP
  - AGO
  - AGRI
  - AGRO
  - AGX
  - AGYS
  - AHCO
  - AHG
  - AHH
  - AHL
  - AHR
  - AHT
  - AI
  - AIFE
  - AIFER
  - AIFEU
  - AIFF
  - AIFU
  - AIG
  - AIHS
  - AII
  - AIM
  - AIMD
  - AIMDW
  - AIN
  - AIO
  - AIOT
  - AIP
  - AIR
  - AIRE
  - AIRG
  - AIRI
  - AIRJ
  - AIRJW
  - AIRO
  - AIRS
  - AIRT
  - AIRTP
  - AISP
  - AISPW
  - AIT
  - AIV
  - AIXI
  - AIZ
  - AIZN
  - AJG
  - AKA
  - AKAM
  - AKAN
  - AKBA
  - AKR
  - AKRO
  - AKTX
  - AKYA
  - AL
  - ALAB
  - ALAR
  - ALB
  - ALBT
  - ALC
  - ALCO
  - ALCY
  - ALDF
  - ALDFU
  - ALDFW
  - ALDX
  - ALE
  - ALEC
  - ALEX
  - ALF
  - ALFUW
  - ALG
  - ALGM
  - ALGN
  - ALGS
  - ALGT
  - ALHC
  - ALIT
  - ALK
  - ALKS
  - ALKT
  - ALL
  - ALLE
  - ALLO
  - ALLR
  - ALLT
  - ALLY
  - ALMS
  - ALMU
  - ALNT
  - ALNY
  - ALOT
  - ALRM
  - ALRS
  - ALSN
  - ALT
  - ALTG
  - ALTI
  - ALTO
  - ALTS
  - ALUR
  - ALV
  - ALVO
  - ALVOW
  - ALX
  - ALXO
  - ALZN
  - AM
  - AMAL
  - AMAT
  - AMBA
  - AMBC
  - AMBI
  - AMBO
  - AMBP
  - AMBR
  - AMC
  - AMCR
  - AMCX
  - AMD
  - AME
  - AMED
  - AMG
  - AMGN
  - AMH
  - AMIX
  - AMKR
  - AMLX
  - AMN
  - AMOD
  - AMODW
  - AMP
  - AMPG
  - AMPGW
  - AMPH
  - AMPL
  - AMPX
  - AMPY
  - AMR
  - AMRC
  - AMRK
  - AMRN
  - AMRX
  - AMRZ
  - AMS
  - AMSC
  - AMSF
  - AMST
  - AMT
  - AMTB
  - AMTD
  - AMTM
  - AMTX
  - AMWD
  - AMWL
  - AMX
  - AMZE
  - AMZN
  - AN
  - ANAB
  - ANDE
  - ANEB
  - ANET
  - ANF
  - ANGH
  - ANGHW
  - ANGI
  - ANGO
  - ANIK
  - ANIP
  - ANIX
  - ANL
  - ANNA
  - ANNAW
  - ANNX
  - ANPA
  - ANRO
  - ANSC
  - ANSCU
  - ANSCW
  - ANSS
  - ANTA
  - ANTE
  - ANTX
  - ANVS
  - ANY
  - AOD
  - AOMD
  - AOMN
  - AOMR
  - AON
  - AORT
  - AOS
  - AOSL
  - AOUT
  - AP
  - APA
  - APAM
  - APD
  - APDN
  - APEI
  - APG
  - APGE
  - APH
  - API
  - APLD
  - APLE
  - APLM
  - APLMW
  - APLS
  - APLT
  - APM
  - APO
  - APOG
  - APOS
  - APP
  - APPF
  - APPN
  - APPS
  - APRE
  - APT
  - APTV
  - APUS
  - APVO
  - APWC
  - APYX
  - AQB
  - AQMS
  - AQN
  - AQNB
  - AQST
  - AR
  - ARAI
  - ARAY
  - ARBB
  - ARBE
  - ARBEW
  - ARBK
  - ARBKL
  - ARCB
  - ARCC
  - ARCO
  - ARCT
  - ARDC
  - ARDT
  - ARDX
  - ARE
  - AREB
  - AREBW
  - AREC
  - AREN
  - ARES
  - ARGD
  - ARGX
  - ARHS
  - ARI
  - ARIS
  - ARKO
  - ARKOW
  - ARKR
  - ARL
  - ARLO
  - ARLP
  - ARM
  - ARMK
  - ARMN
  - ARMP
  - AROC
  - AROW
  - ARQ
  - ARQQ
  - ARQQW
  - ARQT
  - ARR
  - ARRY
  - ARTL
  - ARTNA
  - ARTV
  - ARTW
  - ARVN
  - ARW
  - ARWR
  - AS
  - ASA
  - ASAN
  - ASB

